# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trmm-secretstore
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  provider: azure
  secretObjects:
  - data:
    - key: postgresuserkey
      objectName: PostgresUser
    secretName: postgresuser
    type: Opaque
  - data:
    - key: postgrespasskey
      objectName: PostgresPass
    secretName: postgrespass
    type: Opaque
  - data:
    - key: meshuserkey
      objectName: MeshUser
    secretName: meshuser
    type: Opaque
  - data:
    - key: meshpasskey
      objectName: MeshPass
    secretName: meshpass
    type: Opaque
  - data:
    - key: mongouserkey
      objectName: MongoUser
    secretName: mongouser
    type: Opaque
  - data:
    - key: mongopasskey
      objectName: MongoPass
    secretName: mongopass
    type: Opaque
  - data:
    - key: trmmuserkey
      objectName: TrmmUser
    secretName: trmmuser
    type: Opaque
  - data:
    - key: trmmpasskey
      objectName: TrmmPass
    secretName: trmmpass
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "c0563e9b-9a5b-4c53-b83f-f73944fcfd96"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "trmm-vault"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: PostgresUser
          objectType: secret
        - |
          objectName: PostgresPass
          objectType: secret
        - |
          objectName: MeshUser
          objectType: secret
        - |
          objectName: MeshPass
          objectType: secret
        - |
          objectName: MongoUser
          objectType: secret
        - |
          objectName: MongoPass
          objectType: secret
        - |
          objectName: TrmmUser
          objectType: secret
        - |
          objectName: TrmmPass
          objectType: secret
    tenantId: "0819678a-52f9-44d6-9ccb-9d3942559a2c" # az account show | grep tenantId