apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  storageClassName: static-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi