apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: storage
  storageClassName: static-disk