apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-storage
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: "trmm-resources"
  storageAccount: "trmmstorage"
  server: trmmstorage.file.core.windows.net 
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage
spec:
  storageClassName: shared-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: sharedstorage1  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      shareName: sharedstorage
    nodeStageSecretRef:
      name: azure-secret
      namespace: tacticalrmm
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
spec:
  storageClassName: shared-storage
  volumeName: shared-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: static-disk
  namespace: tacticalrmm
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  capacity:
    storage: 16Gi
  storageClassName: static-disk
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: postgres
    diskURI: /subscriptions/522a3c55-d74a-4f1e-a543-815597de6ede/resourceGroups/trmm-resources/providers/Microsoft.Compute/disks/postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
    storage: 16Gi
  storageClassName: static-disk
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: mongodb
    diskURI: /subscriptions/522a3c55-d74a-4f1e-a543-815597de6ede/resourceGroups/trmm-resources/providers/Microsoft.Compute/disks/mongodb

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: meshdata
spec:
  capacity:
    storage: 16Gi
  storageClassName: static-disk
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: meshdata
    diskURI: /subscriptions/522a3c55-d74a-4f1e-a543-815597de6ede/resourceGroups/trmm-resources/providers/Microsoft.Compute/disks/meshdata

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  capacity:
    storage: 16Gi
  storageClassName: static-disk
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: redis
    diskURI: /subscriptions/522a3c55-d74a-4f1e-a543-815597de6ede/resourceGroups/trmm-resources/providers/Microsoft.Compute/disks/redis