apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: tacticalrmm
type: Opaque
stringData:
  azurestorageaccountkey: {{ .Values.storage.key }}
  azurestorageaccountname: {{ .Values.storage.account }}

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trmm-secretstore
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  provider: azure
  secretObjects:
  - data:
    - key: rmmurlkey
      objectName: RmmUrl
    secretName: rmmurl
    type: Opaque
  - data:
    - key: apiurlkey
      objectName: ApiUrl
    secretName: apiurl
    type: Opaque
  - data:
    - key: meshurlkey
      objectName: MeshUrl
    secretName: meshurl
    type: Opaque
  - data:
    - key: postgresuserkey
      objectName: PostgresUser
    secretName: postgresuser
    type: Opaque
  - data:
    - key: postgrespasskey
      objectName: PostgresPass
    secretName: postgrespass
    type: Opaque
  - data:
    - key: meshuserkey
      objectName: MeshUser
    secretName: meshuser
    type: Opaque
  - data:
    - key: meshpasskey
      objectName: MeshPass
    secretName: meshpass
    type: Opaque
  - data:
    - key: mongouserkey
      objectName: MongoUser
    secretName: mongouser
    type: Opaque
  - data:
    - key: mongopasskey
      objectName: MongoPass
    secretName: mongopass
    type: Opaque
  - data:
    - key: trmmuserkey
      objectName: TrmmUser
    secretName: trmmuser
    type: Opaque
  - data:
    - key: trmmpasskey
      objectName: TrmmPass
    secretName: trmmpass
    type: Opaque
  - data:
    - key: trmmcertkey
      objectName: TrmmCert
    secretName: trmmcert
    type: Opaque
  - data:
    - key: trmmkeykey
      objectName: TrmmKey
    secretName: trmmkey
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentity }}
    keyvaultName: {{ .Values.keyvault }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: RmmUrl
          objectType: secret
        - |
          objectName: ApiUrl
          objectType: secret
        - |
          objectName: MeshUrl
          objectType: secret
        - |
          objectName: PostgresUser
          objectType: secret
        - |
          objectName: PostgresPass
          objectType: secret
        - |
          objectName: MeshUser
          objectType: secret
        - |
          objectName: MeshPass
          objectType: secret
        - |
          objectName: MongoUser
          objectType: secret
        - |
          objectName: MongoPass
          objectType: secret
        - |
          objectName: TrmmUser
          objectType: secret
        - |
          objectName: TrmmPass
          objectType: secret
        - |
          objectName: TrmmCert
          objectType: secret
        - |
          objectName: TrmmKey
          objectType: secret
    tenantId: {{ .Values.tenantId }}