apiVersion: v1
kind: Service
metadata:
  name: tactical-frontend
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  selector:
    app: tactical-frontend
  ports:
    - port: 8080
      name: "frontendport"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-frontend
  namespace: tacticalrmm
  labels:
    app: tactical-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-frontend
  template:
    metadata:
      labels:
        app: tactical-frontend
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: tactical-frontend
          image: "{{ .Values.containerRegistry }}.azurecr.io/tactical-frontend:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: apiurl
                  key: apiurlkey
          volumeMounts:
          - name: trmm-secretstore-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: trmm-secretstore-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "trmm-secretstore"