apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbdata
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  volumeName: mongodb
  storageClassName: static-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi

---

apiVersion: v1
kind: Service
metadata:
  name: tactical-mongodb
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  selector:
    app: tactical-mongodb
  ports:
    - port: 27017
      name: "mongodbport"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-mongodb
  namespace: tacticalrmm
  labels:
    app: tactical-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-mongodb
  template:
    metadata:
      labels:
        app: tactical-mongodb
    spec:
      containers:
        - name: tactical-mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
              name: tcp
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongouser
                  key: mongouserkey
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopass
                  key: mongopasskey
            - name: MONGO_INITDB_DATABASE
              value: "meshcentral"
          volumeMounts:
            - name: storage
              mountPath: /data/db
            - name: trmm-secretstore-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongodbdata
        - name: trmm-secretstore-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "trmm-secretstore"
