apiVersion: v1
kind: Service
metadata:
  name: tactical-backend
  namespace: tacticalrmm
  labels:
    app: trmm
spec:
  selector:
    app: tactical-backend
  ports:
    - port: 8080
      name: "backendport"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-backend
  namespace: tacticalrmm
  labels:
    app: tactical-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-backend
  template:
    metadata:
      labels:
        app: tactical-backend
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: tactical-backend
          args: ["tactical-backend"]
          image: "{{ .Values.containerRegistry }}.azurecr.io/tactical:{{ .Values.image.tag }}"
          volumeMounts:
            - name: storage
              mountPath: /opt/tactical
          ports:
            - containerPort: 8080
              name: http
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: shared-storage